# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jdk: [8, 16]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
      AUDIODEV: "null"

    steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
     
     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
         java-version: ${{ matrix.jdk }}
         distribution: 'adopt'
         
     - name: Cache Maven packages
       uses: actions/cache@v2
       with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
         
     - name: Run build
       uses: GabrielBB/xvfb-action@v1
       with:
         if: $${{ !contains(matrix.os, 'ubuntu-latest') || matrix.jdk != '8' }}
         run: mvn clean install --file lionengine-parent/pom.xml
         
     - name: Run sonar
       uses: GabrielBB/xvfb-action@v1
       with:
         if: $${{ contains(matrix.os, 'ubuntu-latest') && matrix.jdk == '8' }}
         run: mvn clean verify --file lionengine-parent/pom.xml -Ptravis -U -Dsonar.organization=b3dgs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=5524bf449ca45fcdb334698371466398321f3a82
